### ISSUE TITLE
Questions on usage..

### ISSUE THREAD

**Issue by terial** [svpcom/wifibroadcast_osd#1]
Hey svpcom! Do you have any tips or examples on how to get your osd up and running? Tried to run it with no additional commands and did not see anything come up on usage. Appreciated.. Thanks!

**Comment by svpcom** [comment]
It listen for mavlink packets on port 14550. You can use mavproxy or mavlink-routerd to route mavlink messages.  Sample usage flow is described in https://github.com/svpcom/wifibroadcast/wiki/Enhanced-setup OSD and video player was tested on Pi Model B and Pi Zero.  OSD screen config is stored in ``osd_config.c`` this is contents of EEPROM of original playuavosd. So you can use https://github.com/TobiasBales/PlayuavOSDConfigurator and convert its output to this file.

**Comment by terial** [comment]
Thanks, currently I have an RPI3 running mavlink-router. I have mavlink router listening on /dev/ttyAMA0 connected to the pixhawks serial2 port. Can i just use one of the UDP ports (like 127.0.0.1:14551) and just cat the stream to wifibroadcast_osd?

**Comment by svpcom** [comment]
Yes. If you need to customize UDP port in wifibroadcast_osd change it in main.c line 97
``` .c
 fd = open_udp_socket_for_rx(14550);
```

**Comment by geofrancis** [comment]
how do i get this working on a regular ezwifibroadcast image?

**Comment by svpcom** [comment]
1. Run wifibroadcast_osd binary. It will listen on UDP 14550.
2. Route telemetry mavlink stream to this port.

To route mavlink stream from UART to UDP you can use mavlink-router or mavproxy.

**Comment by svpcom** [comment]
Added to readme
