### ISSUE TITLE
required packages

### ISSUE THREAD

**Issue by terial** [svpcom/wifibroadcast_osd#2]
I had a list somewhere of the packages required to build the OSD but i am having issues now. Is it possible to get the required package list to build the OSD? I would be glad to help document the process since I see you are looking to add some documentation in the future...?

This is the error message I get when running make

cc -c -o osdconfig.o osdconfig.c -g -Wall -std=gnu99 -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
cc -c -o osdvar.o osdvar.c -g -Wall -std=gnu99 -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
cc -c -o fonts.o fonts.c -g -Wall -std=gnu99 -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
cc -c -o font_outlined8x14.o font_outlined8x14.c -g -Wall -std=gnu99 -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
cc -c -o font_outlined8x8.o font_outlined8x8.c -g -Wall -std=gnu99 -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
cc -c -o oglinit.o oglinit.c -g -Wall -std=gnu99 -I/opt/vc/include/ -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
cc -o osd main.o osdrender.o osdmavlink.o graphengine.o UAVObj.o m2dlib.o math3d.o osdconfig.o osdvar.o fonts.o font_outlined8x14.o font_outlined8x8.o oglinit.o -L/opt/vc/lib/ -lGLESv2 -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -lm
/usr/bin/ld: oglinit.o: undefined reference to symbol 'glLoadIdentity'
//opt/vc/lib/libbrcmGLESv2.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:10: recipe for target 'osd' failed
make: *** [osd] Error 1

trying things out on stretch lite.

**Comment by svpcom** [comment]
See docker/Dockerfile:
```
libraspberrypi0 libraspberrypi-dev libraspberrypi-doc libraspberrypi-bin
```

Anyway, a preferred build scheme is to using cross-compiler via docker: ``make build_rpi``

**Comment by terial** [comment]
Thanks svpcom, as you can tell I have much to learn. I am not familiar with docker but will do some research. Thanks again for you guidance and help. I will hopefully get some success and can possibly help you with documentation down the road!
