### ISSUE TITLE
Issue on running make build_rpi 

### ISSUE THREAD

**Issue by awaisali88** [svpcom/wifibroadcast_osd#3]
I am having issue on running the make command with build_rpi. The issue is generating with docker file. I am trying to compile it on raspberry pi 3 b+ with raspbian buster lite and also tried raspberry pi 4 b (2gb) model.

first i was getting issue 
standard_init_linux.go:207 exec user process caused "exec format error"

Then after some research i find out that it need qemu packages so I installed those packages with this command. 
sudo apt install binfmt-support qemu qemu-user-static qemu-system qemu-system-arm

Now i am getting a different error. 
Unable to reserve 0xf7000000 bytes of virtual address space for use as guest address space (check your virtual memory ulimit setting or reserve less using -R option)

I can't seem to find the solution of it.

**Comment by svpcom** [comment]
Use `make deb` for native build

**Comment by awaisali88** [comment]
Thanks for your prompt response.

make deb command did not work and there is not deb option in makefile. 

I am sorry if it is stupid question as I don't have much experience with linux systems.

**Comment by svpcom** [comment]
For native build on raspberry pi: `make osd mode=rpi`
